CREATE USER 'administrador'@'localhost' IDENTIFIED BY '#Admin#16*'; 
GRANT SELECT,DELETE ON carrilloofrece.persona TO 'administrador'@'localhost' IDENTIFIED BY '#Admin#16*';
GRANT SELECT,DELETE ON carrilloofrece.usuario TO 'administrador'@'localhost';
GRANT SELECT,DELETE ON carrilloofrece.calificacion_usuario TO 'administrador'@'localhost';
GRANT SELECT,DELETE,UPDATE ON carrilloofrece.producto TO 'administrador'@'localhost';
GRANT SELECT ON carrilloofrece.categoria_producto TO 'admiistrador'@'localhost';
GRANT SELECT,DELETE ON carrilloofrece.notificacion TO 'administrador'@'localhost0';
GRANT SELECT,DELETE ON carrilloofrece.denuncia_producto TO 'administrador'@'localhost';
GRANT SELECT,DELETE,UPDATE ON carrilloofrece.negocio TO 'administrador'@'localhost';
GRANT SELECT ON carrilloofrece.categoria_negocio TO 'administrador'@'localhost';
GRANT SELECT ON carrilloofrece.colonia_negocio TO 'administrador'@'localhost';
GRANT SELECT,DELETE ON carrilloofrece.denuncia_negocio TO 'administrador'@'localhost';
GRANT SELECT,DELETE ON carrilloofrece.horario_negocio TO 'administrador'@'localhost';
GRANT SELECT,DELETE ON carrilloofrece.calificacion_negocio TO 'administrador'@'localhost';
GRANT SELECT,DELETE,UPDATE ON carrilloofrece.servicio TO 'admiistrador'@'localhost';
GRANT SELECT ON carrilloofrece.categoria_servicio TO 'administrador'@'localhost';
GRANT SELECT ON carrilloofrece.colonia_servicio TO 'administrador'@'localhost';
GRANT SELECT,DELETE ON carrilloofrece.denuncia_servicio TO 'administrador'@'localhost';
GRANT SELECT,DELETE ON carrilloofrece.horario_servicio TO 'administrador'@'localhost';
GRANT SELECT,DELETE ON carrilloofrece.calificacion_servicio TO 'administrador'@'localhost';
FLUSH PRIVILEGES;

CREATE USER 'usuario_normal'@'localhost' IDENTIFIED BY '*Usunormal#75';
GRANT SELECT,INSERT,UPDATE ON carrilloofrece.persona TO 'usuario_normal'@'localhost';
GRANT SELECT,INSERT,UPDATE ON carrilloofrece.usuario TO 'usuario_normal'@'localhost';
GRANT SELECT,INSERT ON carrilloofrece.calificacion_usuario TO 'usuario_normal'@'localhost';
GRANT SELECT,INSERT,UPDATE,DELETE ON carrilloofrece.producto TO 'usuario_normal'@'localhost';
GRANT SELECT ON carrilloofrece.categoria_producto TO 'usuario_normal'@'localhost';
GRANT SELECT,INSERT,DELETE ON carrilloofrece.notificacion TO 'usuario_normal'@'localhost0';
GRANT SELECT,INSERT,DELETE ON carrilloofrece.denuncia_producto TO 'usuario_normal'@'localhost';
GRANT SELECT,INSERT,UPDATE,DELETE ON carrilloofrece.negocio TO 'usuario_normal'@'localhost';
GRANT SELECT ON carrilloofrece.categoria_negocio TO 'usuario_normal'@'localhost';
GRANT SELECT,INSERT,UPDATE ON carrilloofrece.colonia_negocio TO 'usuario_normal'@'localhost';
GRANT SELECT,INSERT,DELETE ON carrilloofrece.denuncia_negocio TO 'usuario_normal'@'localhost';
GRANT SELECT,INSERT,UPDATE,DELETE ON carrilloofrece.horario_negocio TO 'usuario_normal'@'localhost';
GRANT SELECT,INSERT ON carrilloofrece.calificacion_negocio TO 'usuario_normal'@'localhost';
GRANT SELECT,INSERT,UPDATE,DELETE ON carrilloofrece.servicio TO 'usuario_normal'@'localhost';
GRANT SELECT ON carrilloofrece.categoria_servicio TO 'usuario_normal'@'localhost';
GRANT SELECT,INSERT,UPDATE ON carrilloofrece.colonia_servicio TO 'usuario_normal'@'localhost';
GRANT SELECT,INSERT,DELETE ON carrilloofrece.denuncia_servicio TO 'usuario_normal'@'localhost';
GRANT SELECT,INSERT,UPDATE,DELETE ON carrilloofrece.horario_servicio TO 'usuario_normal'@'localhost';
GRANT SELECT,INSERT ON carrilloofrece.calificacion_servicio TO 'usuario_normal'@'localhost';
FLUSH PRIVILEGES;
